env:
  browser: true
  es6: true
extends:
  - google
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
ignorePatterns:
  - 'webpack.config.js'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  'valid-jsdoc': 'off'
  'require-jsdoc': 'off'
